// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3enrNTuDQfTrviLHwnqsphcnwovQ7ho',
    appId: '1:152096645156:web:e91800877e5d423489b8b1',
    messagingSenderId: '152096645156',
    projectId: 'vs6451071059',
    authDomain: 'vs6451071059.firebaseapp.com',
    storageBucket: 'vs6451071059.firebasestorage.app',
    measurementId: 'G-G8HBNL4L8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZHe4tj0UofVpcIemkZ7_crgA8d2KB0Mk',
    appId: '1:152096645156:android:df1483d27bc2d32989b8b1',
    messagingSenderId: '152096645156',
    projectId: 'vs6451071059',
    storageBucket: 'vs6451071059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcLR7tnL5TDzWXSrT38nLYXIC5jVW7BX4',
    appId: '1:152096645156:ios:08d0666460a5d27f89b8b1',
    messagingSenderId: '152096645156',
    projectId: 'vs6451071059',
    storageBucket: 'vs6451071059.firebasestorage.app',
    iosBundleId: 'com.example.quanLyQuanTs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcLR7tnL5TDzWXSrT38nLYXIC5jVW7BX4',
    appId: '1:152096645156:ios:08d0666460a5d27f89b8b1',
    messagingSenderId: '152096645156',
    projectId: 'vs6451071059',
    storageBucket: 'vs6451071059.firebasestorage.app',
    iosBundleId: 'com.example.quanLyQuanTs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy3enrNTuDQfTrviLHwnqsphcnwovQ7ho',
    appId: '1:152096645156:web:40bed8c3e733cbf889b8b1',
    messagingSenderId: '152096645156',
    projectId: 'vs6451071059',
    authDomain: 'vs6451071059.firebaseapp.com',
    storageBucket: 'vs6451071059.firebasestorage.app',
    measurementId: 'G-KT0YLBNJ2W',
  );
}
